## Importing

In [40]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

## Reading Data

In [2]:
train_data = pd.read_csv("/home/sysadm/F1nalyze/train.csv")
validation_data = pd.read_csv("/home/sysadm/F1nalyze/validation.csv")
test_data = pd.read_csv("/home/sysadm/F1nalyze/test.csv")

/tmp/ipykernel_7678/1946800243.py:1: DtypeWarning: Columns (4,13,14,16,47) have mixed types. Specify dtype option on import or set low_memory=False.
  train_data = pd.read_csv("/home/sysadm/F1nalyze/train.csv")
/tmp/ipykernel_7678/1946800243.py:2: DtypeWarning: Columns (13,16,36) have mixed types. Specify dtype option on import or set low_memory=False.
  validation_data = pd.read_csv("/home/sysadm/F1nalyze/validation.csv")
/tmp/ipykernel_7678/1946800243.py:3: DtypeWarning: Columns (13,16) have mixed types. Specify dtype option on import or set low_memory=False.
  test_data = pd.read_csv("/home/sysadm/F1nalyze/test.csv")

## Fixing Train Data

In [3]:
train_data

,resultId,racerId,driverId,constructorId,number,grid,position_x,positionText_x,positionOrder,points,...,points_y,position,positionText_y,wins,constructorRef,company,nationality_y,url,status,result_driver_standing
0,20025,833,642,51,2,1,1,1,1,9.0,...,3.33,3,3,0,alfa,Alfa Romeo,Swiss,http://en.wikipedia.org/wiki/Alfa_Romeo_in_For...,Finished,922731975
1,20025,833,642,51,2,1,1,1,1,9.0,...,6.33,3,3,0,alfa,Alfa Romeo,Swiss,http://en.wikipedia.org/wiki/Alfa_Romeo_in_For...,Finished,923172525
2,20025,833,642,51,2,1,1,1,1,9.0,...,6.33,4,4,0,alfa,Alfa Romeo,Swiss,http://en.wikipedia.org/wiki/Alfa_Romeo_in_For...,Finished,923833350
3,20025,833,642,51,2,1,1,1,1,9.0,...,10.33,3,3,0,alfa,Alfa Romeo,Swiss,http://en.wikipedia.org/wiki/Alfa_Romeo_in_For...,Finished,925195050
4,20025,833,642,51,2,1,1,1,1,9.0,...,10.33,4,4,0,alfa,Alfa Romeo,Swiss,http://en.wikipedia.org/wiki/Alfa_Romeo_in_For...,Finished,926576775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2830096,22109,899,17,9,2,4,2,2,2,18.0,...,61.50,4,4,2,red_bull,Red Bull,Austrian,http://en.wikipedia.org/wiki/Red_Bull_Racing,Finished,401167805
2830097,22109,899,17,9,2,4,2,2,2,18.0,...,69.50,4,4,2,red_bull,Red Bull,Austrian,http://en.wikipedia.org/wiki/Red_Bull_Racing,Finished,660484266
2830098,22109,899,17,9,2,4,2,2,2,18.0,...,4.00,8,8,0,red_bull,Red Bull,Austrian,http://en.wikipedia.org/wiki/Red_Bull_Racing,Finished,1409316096
2830099,22109,899,17,9,2,4,2,2,2,18.0,...,6.00,10,10,0,red_bull,Red Bull,Austrian,http://en.wikipedia.org/wiki/Red_Bull_Racing,Finished,1409846712
2830100,22109,899,17,9,2,4,2,2,2,18.0,...,24.00,8,8,0,red_bull,Red Bull,Austrian,http://en.wikipedia.org/wiki/Red_Bull_Racing,Finished,1410377328

In [4]:
train_data.replace('\\N', np.nan, inplace=True)

na_counts = train_data.isna().sum()

print(na_counts)

resultId                        0
racerId                         0
driverId                        0
constructorId                   0
number                        160
grid                            0
position_x                1125357
positionText_x                  0
positionOrder                   0
points                          0
laps                            0
time_x                    1871686
timetaken_in_millisec     1871741
fastestLap                2112010
rank                      2105375
fastestLapTime            2112010
max_speed                 2112010
statusId                        0
year                            0
round                           0
circuitId                       0
grand_prix                      0
date                            0
time_y                    2150026
url_x                           0
fp1_date                  2830101
fp1_time                  2830101
fp2_date                  2830101
fp2_time                  2830101
fp3_date                  2830101
fp3_time                  2830101
quali_date                2830101
quali_time                2830101
sprint_date               2830101
sprint_time               2830101
driverRef                       0
driver_num                2354922
driver_code               1731200
forename                        0
surname                         0
dob                             0
nationality                     0
url_y                           0
driverStandingsId               0
raceId_y                        0
points_y                        0
position                        0
positionText_y                  0
wins                            0
constructorRef                  0
company                         0
nationality_y                   0
url                             0
status                          0
result_driver_standing          0
dtype: int64

In [5]:
train_data.drop(columns = ["resultId","racerId","driverId","constructorId","position_x","time_x","timetaken_in_millisec","date","time_y","url_x","fp1_date",
                           "fp1_time","fp2_date","fp2_time","fp3_date","fp3_time","quali_date","quali_time","sprint_date","sprint_time","driver_num","driver_code","forename",
                           "surname","dob","url_y","driverStandingsId","raceId_y","positionText_y","constructorRef","url"], inplace=True)

In [6]:
train_data.dropna(inplace= True)

In [7]:
train_data

,number,grid,positionText_x,positionOrder,points,laps,fastestLap,rank,fastestLapTime,max_speed,...,grand_prix,driverRef,nationality,points_y,position,wins,company,nationality_y,status,result_driver_standing
2082849,1,1,1,1,10.0,58,29,1,1:24.125,226.933,...,Australian Grand Prix,michael_schumacher,German,8.0,2,0,Ferrari,Italian,Finished,19404120
2082850,1,1,1,1,10.0,58,29,1,1:24.125,226.933,...,Australian Grand Prix,michael_schumacher,German,11.0,2,0,Ferrari,Italian,Finished,19431390
2082851,1,1,1,1,10.0,58,29,1,1:24.125,226.933,...,Australian Grand Prix,michael_schumacher,German,11.0,4,0,Ferrari,Italian,Finished,19463205
2082852,1,1,1,1,10.0,58,29,1,1:24.125,226.933,...,Australian Grand Prix,michael_schumacher,German,21.0,2,1,Ferrari,Italian,Finished,19496535
2082853,1,1,1,1,10.0,58,29,1,1:24.125,226.933,...,Australian Grand Prix,michael_schumacher,German,31.0,2,2,Ferrari,Italian,Finished,19529865
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2830096,2,4,2,2,18.0,71,51,1,1:15.436,205.636,...,Brazilian Grand Prix,webber,Australian,61.5,4,2,Red Bull,Austrian,Finished,401167805
2830097,2,4,2,2,18.0,71,51,1,1:15.436,205.636,...,Brazilian Grand Prix,webber,Australian,69.5,4,2,Red Bull,Austrian,Finished,660484266
2830098,2,4,2,2,18.0,71,51,1,1:15.436,205.636,...,Brazilian Grand Prix,webber,Australian,4.0,8,0,Red Bull,Austrian,Finished,1409316096
2830099,2,4,2,2,18.0,71,51,1,1:15.436,205.636,...,Brazilian Grand Prix,webber,Australian,6.0,10,0,Red Bull,Austrian,Finished,1409846712
2830100,2,4,2,2,18.0,71,51,1,1:15.436,205.636,...,Brazilian Grand Prix,webber,Australian,24.0,8,0,Red Bull,Austrian,Finished,1410377328

In [8]:
def time_to_seconds(time_str):
    minutes, seconds = time_str.split(':')
    total_seconds = int(minutes) * 60 + float(seconds)
    return total_seconds

train_data["fastestLapTime"] = train_data["fastestLapTime"].apply(time_to_seconds)

In [9]:
train_data["number"] = train_data["number"].astype(int)
train_data["fastestLap"] = train_data["fastestLap"].astype(int)
train_data["rank"] = train_data["rank"].astype(int)
train_data["max_speed"] = train_data["max_speed"].astype(float)

In [10]:
encoder = LabelEncoder()
train_data["positionText_x"] = encoder.fit_transform(train_data["positionText_x"])
train_data["grand_prix"] = encoder.fit_transform(train_data["grand_prix"])
train_data["driverRef"] = encoder.fit_transform(train_data["driverRef"])
train_data["nationality"] = encoder.fit_transform(train_data["nationality"])
train_data["company"] = encoder.fit_transform(train_data["company"])
train_data["nationality_y"] = encoder.fit_transform(train_data["nationality_y"])
train_data["status"] = encoder.fit_transform(train_data["status"])

In [11]:
train_data.dtypes

number                      int64
grid                        int64
positionText_x              int64
positionOrder               int64
points                    float64
laps                        int64
fastestLap                  int64
rank                        int64
fastestLapTime            float64
max_speed                 float64
statusId                    int64
year                        int64
round                       int64
circuitId                   int64
grand_prix                  int64
driverRef                   int64
nationality                 int64
points_y                  float64
position                    int64
wins                        int64
company                     int64
nationality_y               int64
status                      int64
result_driver_standing      int64
dtype: object

In [12]:
train_data

,number,grid,positionText_x,positionOrder,points,laps,fastestLap,rank,fastestLapTime,max_speed,...,grand_prix,driverRef,nationality,points_y,position,wins,company,nationality_y,status,result_driver_standing
2082849,1,1,0,1,10.0,58,29,1,84.125,226.933,...,1,40,11,8.0,2,0,4,7,33,19404120
2082850,1,1,0,1,10.0,58,29,1,84.125,226.933,...,1,40,11,11.0,2,0,4,7,33,19431390
2082851,1,1,0,1,10.0,58,29,1,84.125,226.933,...,1,40,11,11.0,4,0,4,7,33,19463205
2082852,1,1,0,1,10.0,58,29,1,84.125,226.933,...,1,40,11,21.0,2,1,4,7,33,19496535
2082853,1,1,0,1,10.0,58,29,1,84.125,226.933,...,1,40,11,31.0,2,2,4,7,33,19529865
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2830096,2,4,11,2,18.0,71,51,1,75.436,205.636,...,4,65,1,61.5,4,2,17,0,33,401167805
2830097,2,4,11,2,18.0,71,51,1,75.436,205.636,...,4,65,1,69.5,4,2,17,0,33,660484266
2830098,2,4,11,2,18.0,71,51,1,75.436,205.636,...,4,65,1,4.0,8,0,17,0,33,1409316096
2830099,2,4,11,2,18.0,71,51,1,75.436,205.636,...,4,65,1,6.0,10,0,17,0,33,1409846712
2830100,2,4,11,2,18.0,71,51,1,75.436,205.636,...,4,65,1,24.0,8,0,17,0,33,1410377328

## Fixing Validation Data

In [13]:
validation_data.replace('\\N', np.nan, inplace=True)
na_counts = validation_data.isna().sum()
print(na_counts)

resultId                       0
racerId                        0
driverId                       0
constructorId                  0
number                         0
grid                           0
position_x                 62123
positionText_x                 0
positionOrder                  0
points                         0
laps                           0
time_x                    155366
timetaken_in_millisec     155366
fastestLap                 16390
rank                           0
fastestLapTime             16390
max_speed                  16390
statusId                       0
year                           0
round                          0
circuitId                      0
grand_prix                     0
date                           0
time_y                         0
url_x                          0
fp1_date                  353762
fp1_time                  353762
fp2_date                  353762
fp2_time                  353762
fp3_date                  353762
fp3_time                  353762
quali_date                353762
quali_time                353762
sprint_date               353762
sprint_time               353762
driverRef                      0
driver_num                   379
driver_code                    0
forename                       0
surname                        0
dob                            0
nationality                    0
url_y                          0
driverStandingsId              0
raceId_y                       0
points_y                       0
position                       0
positionText_y                 0
wins                           0
constructorRef                 0
company                        0
nationality_y                  0
url                            0
status                         0
result_driver_standing         0
dtype: int64

In [14]:
validation_data.drop(columns = ["resultId","racerId","driverId","constructorId","position_x","time_x","timetaken_in_millisec","date","time_y","url_x","fp1_date",
                           "fp1_time","fp2_date","fp2_time","fp3_date","fp3_time","quali_date","quali_time","sprint_date","sprint_time","driver_num","driver_code","forename",
                           "surname","dob","url_y","driverStandingsId","raceId_y","positionText_y","constructorRef","url"], inplace=True)

In [15]:
validation_data.dropna(inplace= True)

In [16]:
validation_data

,number,grid,positionText_x,positionOrder,points,laps,fastestLap,rank,fastestLapTime,max_speed,...,grand_prix,driverRef,nationality,points_y,position,wins,company,nationality_y,status,result_driver_standing
0,2,4,2,2,18.0,71,51,1,1:15.436,205.636,...,Brazilian Grand Prix,webber,Australian,28.0,8,0,Red Bull,Austrian,Finished,1410907944
1,2,4,2,2,18.0,71,51,1,1:15.436,205.636,...,Brazilian Grand Prix,webber,Australian,53.0,4,1,Red Bull,Austrian,Finished,1411438560
2,2,4,2,2,18.0,71,51,1,1:15.436,205.636,...,Brazilian Grand Prix,webber,Australian,78.0,1,2,Red Bull,Austrian,Finished,1412499792
3,2,4,2,2,18.0,71,51,1,1:15.436,205.636,...,Brazilian Grand Prix,webber,Australian,93.0,1,2,Red Bull,Austrian,Finished,1413030408
4,2,4,2,2,18.0,71,51,1,1:15.436,205.636,...,Brazilian Grand Prix,webber,Australian,103.0,3,2,Red Bull,Austrian,Finished,1413561024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353757,14,13,8,8,4.0,70,69,9,1:08.661,226.399,...,Austrian Grand Prix,alonso,Spanish,123.0,1,6,McLaren,British,+1 Lap,1705168800
353758,14,13,8,8,4.0,70,69,9,1:08.661,226.399,...,Austrian Grand Prix,alonso,Spanish,133.0,1,7,McLaren,British,+1 Lap,1705815423
353759,14,13,8,8,4.0,70,69,9,1:08.661,226.399,...,Austrian Grand Prix,alonso,Spanish,6.0,3,0,McLaren,British,+1 Lap,297542376
353760,14,13,8,8,4.0,70,69,9,1:08.661,226.399,...,Austrian Grand Prix,alonso,Spanish,8.0,5,0,McLaren,British,+1 Lap,297877662
353761,14,13,8,8,4.0,70,69,9,1:08.661,226.399,...,Austrian Grand Prix,alonso,Spanish,11.0,5,0,McLaren,British,+1 Lap,298284795

In [17]:
validation_data["fastestLapTime"] = validation_data["fastestLapTime"].apply(time_to_seconds)

In [18]:
validation_data["number"] = validation_data["number"].astype(int)
validation_data["fastestLap"] = validation_data["fastestLap"].astype(int)
validation_data["rank"] = validation_data["rank"].astype(int)
validation_data["max_speed"] = validation_data["max_speed"].astype(float)

In [19]:
encoder = LabelEncoder()
validation_data["positionText_x"] = encoder.fit_transform(validation_data["positionText_x"])
validation_data["grand_prix"] = encoder.fit_transform(validation_data["grand_prix"])
validation_data["driverRef"] = encoder.fit_transform(validation_data["driverRef"])
validation_data["nationality"] = encoder.fit_transform(validation_data["nationality"])
validation_data["company"] = encoder.fit_transform(validation_data["company"])
validation_data["nationality_y"] = encoder.fit_transform(validation_data["nationality_y"])
validation_data["status"] = encoder.fit_transform(validation_data["status"])

In [20]:
validation_data.dtypes

number                      int64
grid                        int64
positionText_x              int64
positionOrder               int64
points                    float64
laps                        int64
fastestLap                  int64
rank                        int64
fastestLapTime            float64
max_speed                 float64
statusId                    int64
year                        int64
round                       int64
circuitId                   int64
grand_prix                  int64
driverRef                   int64
nationality                 int64
points_y                  float64
position                    int64
wins                        int64
company                     int64
nationality_y               int64
status                      int64
result_driver_standing      int64
dtype: object

In [21]:
validation_data

,number,grid,positionText_x,positionOrder,points,laps,fastestLap,rank,fastestLapTime,max_speed,...,grand_prix,driverRef,nationality,points_y,position,wins,company,nationality_y,status,result_driver_standing
0,2,4,11,2,18.0,71,51,1,75.436,205.636,...,6,42,1,28.0,8,0,9,1,20,1410907944
1,2,4,11,2,18.0,71,51,1,75.436,205.636,...,6,42,1,53.0,4,1,9,1,20,1411438560
2,2,4,11,2,18.0,71,51,1,75.436,205.636,...,6,42,1,78.0,1,2,9,1,20,1412499792
3,2,4,11,2,18.0,71,51,1,75.436,205.636,...,6,42,1,93.0,1,2,9,1,20,1413030408
4,2,4,11,2,18.0,71,51,1,75.436,205.636,...,6,42,1,103.0,3,2,9,1,20,1413561024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353757,14,13,20,8,4.0,70,69,9,68.661,226.399,...,2,0,18,123.0,1,6,7,2,0,1705168800
353758,14,13,20,8,4.0,70,69,9,68.661,226.399,...,2,0,18,133.0,1,7,7,2,0,1705815423
353759,14,13,20,8,4.0,70,69,9,68.661,226.399,...,2,0,18,6.0,3,0,7,2,0,297542376
353760,14,13,20,8,4.0,70,69,9,68.661,226.399,...,2,0,18,8.0,5,0,7,2,0,297877662
353761,14,13,20,8,4.0,70,69,9,68.661,226.399,...,2,0,18,11.0,5,0,7,2,0,298284795

## Fixing Test Data

In [22]:
test_data.replace('\\N', np.nan, inplace=True)
na_counts = test_data.isna().sum()

print(na_counts)

resultId                       0
racerId                        0
driverId                       0
constructorId                  0
number                         0
grid                           0
position_x                 45237
positionText_x                 0
positionOrder                  0
points                         0
laps                           0
time_x                    145425
timetaken_in_millisec     145425
fastestLap                 12225
rank                           0
fastestLapTime             12225
max_speed                  12225
statusId                       0
year                           0
round                          0
circuitId                      0
grand_prix                     0
date                           0
time_y                         0
url_x                          0
fp1_date                  177237
fp1_time                  249976
fp2_date                  177237
fp2_time                  249976
fp3_date                  204987
fp3_time                  267989
quali_date                177237
quali_time                249976
sprint_date               325178
sprint_time               334915
driverRef                      0
driver_num                     0
driver_code                    0
forename                       0
surname                        0
dob                            0
nationality                    0
url_y                          0
driverStandingsId              0
raceId_y                       0
points_y                       0
wins                           0
constructorRef                 0
company                        0
nationality_y                  0
url                            0
status                         0
result_driver_standing         0
dtype: int64

In [23]:
test_data.drop(columns = ["resultId","racerId","driverId","constructorId","position_x","time_x","timetaken_in_millisec","date","time_y","url_x","fp1_date",
                           "fp1_time","fp2_date","fp2_time","fp3_date","fp3_time","quali_date","quali_time","sprint_date","sprint_time","driver_num","driver_code","forename",
                           "surname","dob","url_y","driverStandingsId","raceId_y","constructorRef","url"], inplace=True)

In [24]:
test_data['fastestLapTime'] = test_data['fastestLapTime'].apply(lambda x: time_to_seconds(x) if pd.notna(x) else x)

In [25]:
test_data["number"] = test_data["number"].astype(int)
test_data['fastestLap'] = test_data['fastestLap'].apply(lambda x: int(x) if pd.notna(x) else x)
test_data["rank"] = test_data["rank"].astype(int)
test_data["max_speed"] = test_data["max_speed"].apply(lambda x: float(x) if pd.notna(x) else x)

In [26]:
encoder = LabelEncoder()
test_data["positionText_x"] = encoder.fit_transform(test_data["positionText_x"])
test_data["grand_prix"] = encoder.fit_transform(test_data["grand_prix"])
test_data["driverRef"] = encoder.fit_transform(test_data["driverRef"])
test_data["nationality"] = encoder.fit_transform(test_data["nationality"])
test_data["company"] = encoder.fit_transform(test_data["company"])
test_data["nationality_y"] = encoder.fit_transform(test_data["nationality_y"])
test_data["status"] = encoder.fit_transform(test_data["status"])

In [27]:
numerical_columns = ["fastestLap","fastestLapTime","max_speed"]
test_data[numerical_columns] = test_data[numerical_columns].apply(lambda col: col.fillna(col.mean()), axis=0)

In [28]:
na_counts = test_data.isna().sum()

print(na_counts)

number                    0
grid                      0
positionText_x            0
positionOrder             0
points                    0
laps                      0
fastestLap                0
rank                      0
fastestLapTime            0
max_speed                 0
statusId                  0
year                      0
round                     0
circuitId                 0
grand_prix                0
driverRef                 0
nationality               0
points_y                  0
wins                      0
company                   0
nationality_y             0
status                    0
result_driver_standing    0
dtype: int64

In [29]:
test_data.dtypes

number                      int64
grid                        int64
positionText_x              int64
positionOrder               int64
points                    float64
laps                        int64
fastestLap                float64
rank                        int64
fastestLapTime            float64
max_speed                 float64
statusId                    int64
year                        int64
round                       int64
circuitId                   int64
grand_prix                  int64
driverRef                   int64
nationality                 int64
points_y                  float64
wins                        int64
company                     int64
nationality_y               int64
status                      int64
result_driver_standing      int64
dtype: object

In [30]:
test_data

,number,grid,positionText_x,positionOrder,points,laps,fastestLap,rank,fastestLapTime,max_speed,...,circuitId,grand_prix,driverRef,nationality,points_y,wins,company,nationality_y,status,result_driver_standing
0,14,13,18,8,4.0,70,69.000000,9,68.700000,226.399000,...,70,3,2,19,16.0,0,7,2,0,298739826
1,14,13,18,8,4.0,70,69.000000,9,68.700000,226.399000,...,70,3,2,19,21.0,0,7,2,0,299218806
2,14,13,18,8,4.0,70,69.000000,9,68.700000,226.399000,...,70,3,2,19,21.0,0,7,2,0,299697786
3,14,13,18,8,4.0,70,69.000000,9,68.700000,226.399000,...,70,3,2,19,25.0,0,7,2,0,300176766
4,14,13,18,8,4.0,70,69.000000,9,68.700000,226.399000,...,70,3,2,19,25.0,0,7,2,0,300655746
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352923,81,5,21,20,0.0,0,46.738294,0,88.176638,210.857955,...,13,6,23,1,5.0,0,7,2,9,1880337225
352924,81,5,21,20,0.0,0,46.738294,0,88.176638,210.857955,...,13,6,23,1,5.0,0,7,2,9,1881380625
352925,81,5,21,20,0.0,0,46.738294,0,88.176638,210.857955,...,13,6,23,1,17.0,0,7,2,9,1881902325
352926,81,5,21,20,0.0,0,46.738294,0,88.176638,210.857955,...,13,6,23,1,27.0,0,7,2,9,1882424025
352927,81,5,21,20,0.0,0,46.738294,0,88.176638,210.857955,...,13,6,23,1,34.0,0,7,2,9,1882971810

In [36]:
y_train = train_data.pop("position")

In [38]:
y_val = validation_data.pop("position")

In [41]:
scaler_standard = StandardScaler()
x_train = scaler_standard.fit_transform(train_data)
x_val = scaler_standard.fit_transform(validation_data)

In [47]:
x_train = pd.DataFrame(x_train, columns=['number', 'grid', 'positionText_x','positionOrder','points','laps','fastestLap','rank','fastestLapTime','max_speed','statusId','year','round','circuitId','grand_prix','driverRef','nationality','points_y','wins','company','nationality_y','status', 'result_driver_standing'])
x_val = pd.DataFrame(x_val, columns=['number', 'grid', 'positionText_x','positionOrder','points','laps','fastestLap','rank','fastestLapTime','max_speed','statusId','year','round','circuitId','grand_prix','driverRef','nationality','points_y','wins','company','nationality_y','status', 'result_driver_standing'])

In [46]:
x_train

,number,grid,positionText_x,positionOrder,points,laps,fastestLap,rank,fastestLapTime,max_speed,...,circuitId,grand_prix,driverRef,nationality,points_y,wins,company,nationality_y,status,result_driver_standing
0,-1.316965,-1.360697,-1.569108,-1.337165,0.901616,0.177984,-0.652222,-1.389684,-0.555290,1.135800,...,-1.004976,-1.476018,0.264924,0.243717,-0.560856,-0.418568,-1.230345,0.742162,0.449974,-0.772666
1,-1.316965,-1.360697,-1.569108,-1.337165,0.901616,0.177984,-0.652222,-1.389684,-0.555290,1.135800,...,-1.004976,-1.476018,0.264924,0.243717,-0.513764,-0.418568,-1.230345,0.742162,0.449974,-0.772621
2,-1.316965,-1.360697,-1.569108,-1.337165,0.901616,0.177984,-0.652222,-1.389684,-0.555290,1.135800,...,-1.004976,-1.476018,0.264924,0.243717,-0.513764,-0.418568,-1.230345,0.742162,0.449974,-0.772570
3,-1.316965,-1.360697,-1.569108,-1.337165,0.901616,0.177984,-0.652222,-1.389684,-0.555290,1.135800,...,-1.004976,-1.476018,0.264924,0.243717,-0.356789,0.163517,-1.230345,0.742162,0.449974,-0.772516
4,-1.316965,-1.360697,-1.569108,-1.337165,0.901616,0.177984,-0.652222,-1.389684,-0.555290,1.135800,...,-1.004976,-1.476018,0.264924,0.243717,-0.199814,0.745602,-1.230345,0.742162,0.449974,-0.772462
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
718086,-1.161562,-0.866368,-0.347840,-1.177090,2.204822,1.048687,0.599914,-1.389684,-1.282314,0.127483,...,0.409177,-1.010111,1.438536,-1.557129,0.278959,0.745602,0.473586,-1.239857,0.449974,-0.154572
718087,-1.161562,-0.866368,-0.347840,-1.177090,2.204822,1.048687,0.599914,-1.389684,-1.282314,0.127483,...,0.409177,-1.010111,1.438536,-1.557129,0.404539,0.745602,0.473586,-1.239857,0.449974,0.265274
718088,-1.161562,-0.866368,-0.347840,-1.177090,2.204822,1.048687,0.599914,-1.389684,-1.282314,0.127483,...,0.409177,-1.010111,1.438536,-1.557129,-0.623646,-0.418568,0.473586,-1.239857,0.449974,1.477670
718089,-1.161562,-0.866368,-0.347840,-1.177090,2.204822,1.048687,0.599914,-1.389684,-1.282314,0.127483,...,0.409177,-1.010111,1.438536,-1.557129,-0.592251,-0.418568,0.473586,-1.239857,0.449974,1.478529
718090,-1.161562,-0.866368,-0.347840,-1.177090,2.204822,1.048687,0.599914,-1.389684,-1.282314,0.127483,...,0.409177,-1.010111,1.438536,-1.557129,-0.309696,-0.418568,0.473586,-1.239857,0.449974,1.479388

In [48]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators=100)
rf.fit(x_train,y_train)
y_train_pred = rf.predict(x_train)

In [ ]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_train, y_train_pred)
print(f"Mean Squared Error (MSE) on training data: {mse}")